# Email Spam Classification
## (MACHINE LEARNING)
### Submitted By: Fiza Shoaib (ARCH-2510-0117)

### Importing Required Libraries

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [2]:
# Data Set 
df = pd.read_csv("spam.csv", encoding='latin-1')
  
df.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [3]:
# If columns are different, fix them
df = df[['v1', 'v2']]
df.columns = ['label', 'text']

In [4]:
df.head()

  label                                               text
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [5]:
# Converting labels to numbers
df['label'] = df['label'].map({'spam': 1, 'ham': 0})

In [6]:
# Spliting data
X_train, X_test, y_train, y_test = train_test_split(df['text'], df['label'], test_size=0.2, random_state=42)

In [7]:
# Text Preprocessing + TF-IDF vectorization
tfidf = TfidfVectorizer(stop_words='english', max_features=3000)
X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

# Train the model

In [8]:
#Naive Bayes works BEST for spam classification. Using:
model = MultinomialNB()
model.fit(X_train_tfidf, y_train)

MultinomialNB()

In [9]:
# Making predictions
y_pred = model.predict(X_test_tfidf)

In [10]:
# Evaluate
print("Accuracy:", accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.97847533632287
[[965   0]
 [ 24 126]]
              precision    recall  f1-score   support

           0       0.98      1.00      0.99       965
           1       1.00      0.84      0.91       150

    accuracy                           0.98      1115
   macro avg       0.99      0.92      0.95      1115
weighted avg       0.98      0.98      0.98      1115

# Testing with a custom email

In [11]:
sample = ["Congratulations! You won a free iPhone. Click now!"]
sample_tfidf = tfidf.transform(sample)
pred = model.predict(sample_tfidf)[0]
if pred == 1:
    print("This Email is classified as SPAM!")
else:
    print("This Email is classified as HAM-not spam")

This Email is classified as SPAM!

In [13]:
sample = ["Hey, Are we still meeting tomorrow foe Lunch?"]
sample_tfidf = tfidf.transform(sample)
pred = model.predict(sample_tfidf)[0]
if pred == 1:
    print("This Email is classified as SPAM!")
else:
    print("This Email is classified as HAM-not spam")

This Email is classified as HAM-not spam